export const LANG_SW_NAME ='sw';

export const LANG_SW_TRANS = {
  'login': 'Ingia',
  'signin': 'Ingia',
  'register': 'Sajili',
  'signout': 'Ondoka',
  'username': 'Jina la mtumiaji',
  'password': 'Neno-siri',
  'clean':'Misafi',
  'all': 'Mitaro Yote',
  'dirty': 'Michafu',
  'unknown': 'Haijulikana',
  'citizens': 'Wananchi',
  'not_adopted': 'Mitaro isiyo na watu',
  'need': 'MItaro inayohitaji msaada',
  'others': 'Mingineyo',
  'need_help': 'Msaada ',
  'adopted': "Mitaro Iliyotwaliwa",
    /*side-menu translation*/
  'dashboard': 'Dashibodi',
  'map' : 'Ona ramani',
  'ranks': 'Uwiano',
  'report': 'Ripoti',
  'view_drain': 'Ona mitaro',
  'notification': 'Julisha wananchi',
  /*content translations*/
  'title_dashboard': 'Ripoti ya usafi wa mitaro ',
  'title_drains': 'Mitaro iliyochukuliwa  Dar es salaam',
  'title' :'Taarifa ya Jumla ya Usafi',

  'results': 'Matokeo',
  'id': 'Namba',
  'address': 'Mtaa/Mahala',
  'name': 'Jina',
  'report_made': 'Ripoti iliyofanyoka',
  'claimed': 'Iliyochukuliwa',
  'phone_number':'Namba ya Simu',
  'ranks_details': 'Nafasi za usafi kulingana na mitaa',
  'location': 'Chagua Eneo/Sehemu',
  'has': 'Ina',
  'district': 'Wilaya',
  'municipal': 'munispaa',
  'region':'Mkoa',
  'ward': 'Kata',
  'drain_filter':'Mitaro na Maeneo Inapopatikana',
  'choose_address': 'Chagua Eneo/Mtaa',
  'street': 'Mtaa',
  'leader': 'Viongozi wa mtaa',
  'registered': 'Wananchi waliosajiliwa',
  'ward_leader':'Viongozi wa Kata',
  'citizen_population': 'Mgawanyiko wa ongezeko la wananchi',


  /*button*/
  'send': 'Tuma',
  'submit':'Wasilisha',
  'cancel': 'Ghairi',
  'first':'mwanzo',
  'previous': 'nyuma',
  'next': 'mbele',
  'last': 'mwisho',
  'alert': 'Mtaarifu VEO',
  'send_alert': 'Ujumbe wa taahadhari',
  'send_awareness': 'Ujumbe wakuwa makini',
  'message_send': 'Tuma ujumbe',

  /*notification*/
  'message':'Ujumbe umetumwa ',
  'admin': 'Sehemu ya admin',
  'alert_user': 'Ujumbe wa tahadhari',
  'alert_message': ' Msimu wa mvua umekaribia, wataarifu wananchi wako na pia wahakikishe mitaro yao ni misafi.',
  'send_message': ' chagua aina ya ujumbe unaotaka kuutuma ',
  'aware_user': 'UJumbe wa kuwa makini',
  'awareness_message':'Tuma ujumbe kuwa harifu wananchi wako nini umuhimu wa usafi katika mazingira na pia kuwa makini kwenye swala zima la usafi.',
  'modify': 'Badilisha',
  'send_msg': 'Tuma',
  'box-msg': 'ujumbe katika sanduku la ujumbe ',
  'or': 'Au',
//  footer
  'copyright': 'Hatimiliki',
  'all-right':'Haki zote zimehifadhiwa.'
};
