export const LANG_SW_NAME ='sw';

export const LANG_SW_TRANS = {
  'login': 'Ingia',
  'register': 'Sajili',
  'signout': 'Ondoka',
  'clean':'Mitaro misafi',
  'all': 'Mitaro yote',
  'dirty': 'Mitaro michafu',
  'unknown': 'Mitaro isiyojulikana',
  'citizens': 'Wananchi',
  'need_help': 'Msaada unahitajika',
  'need_help_report': 'Ripoti ya mitaro inayohitaji msaada',
  'adopted': "Mitaro iliyotwaliwa",
  'not_adopted': 'Mitaro ambayo haijatwaliwa',
  'need': 'Mitaro inayohitaji msaada',
  'others': 'Mingineyo',
  /*side-menu translation*/
  'dashboard': 'Dashibodi',
  'map' : 'Fungua ramani',
  'ranks': 'Uwiano',
  'report': 'Ripoti',
  'view_drain': 'Ona mitaro',
  'notification': 'Tuma Taarifa',
  /*content translations*/
  'title' :'Usafi wa mitaro yote kwa ujumla',
  'title_dashboard': 'Ripoti ya usafi wa mitaro ilitwaliwa',
  'title_drains': 'Mitaro iliyotwaliwa  Dar es salaam',
  'results': 'Matokeo',
  'id': 'Namba',
  'address': 'Mtaa/Mahala',
  'name': 'Jina',
  'report_made': 'Iliripotiwa',
  'claimed': 'Iliyotwaliwa',
  'phone_number':'Namba ya Simu',
  'ranks_details': 'Nafasi za usafi kulingana na mitaa',
  'location': 'Chagua Eneo/Sehemu',
  'has': 'ina',
  'district': 'Wilaya',
  'municipal': 'Manispaa',
  'region':'Mkoa',
  'ward': 'Kata',
  'street': 'Mtaa',
  'drain_filter':'Mgawanyo wa Mitaro',
  'choose_address': 'Chagua Eneo/Mtaa',
  'leader': 'Viongozi wa mtaa',
  'registered': 'Wananchi waliosajiliwa',
  'ward_leader':'Viongozi wa Kata',
  'citizen_population': 'Mgawanyiko wa watu',
  /*button*/
  'send': 'Tuma',
  'submit':'Wasilisha',
  'first':'Mwanzo',
  'previous': 'Nyuma',
  'next': 'Mbele',
  'last': 'Mwisho',
  'alert': 'Mtarifu VEO',
  /*notification*/
  'message':'Ujumbe umetumwa ',

//  footer
  'copyright': 'Hatimiliki',
  'all-right':'Haki zote zimehifadhiwa.'
};
