export const LANG_EN_NAME ='en';

export const LANG_EN_TRANS = {

  'login': 'Login',
  'signin': 'Sign In',
  'register': 'Register',
  'signout': 'Sign out',
  'username': 'Username',
  'password': 'Password',
  'clean':'Clean Drains',
  'all': 'All Drains',
  'dirty': 'Dirty Drains',
  'unknown': 'Unknown Drains',
  'citizens': 'Citizens',
  'need_help_report': 'Status Report of drains that need help',
  'need_help': 'Need Help',
  'adopted': "Adopted drains",
  'not_adopted': 'Not adopted',
  'others': 'Others',
  'need': 'Drains that need help',
  /*side-menu translation*/
  'dashboard': 'Dashboard',
  'map' : 'View map',
  'ranks': 'Rankings',
  'report': 'Reports',
  'view_drain': 'View Drains',
  'notification': 'Notify citizens',
  /*content translations*/
  'title' :'General Cleanness Report for Drains',
  'title_dashboard': 'General Cleanness Report ',
  'title_drains': 'Drain Adoption in Dar es salaam',
  'results':'Results',
  'id': 'Id',
  'address': 'Address',
  'name': 'Name',
  'claimed': 'Claimed',
  'report_made': 'Report made',
  'phone_number': 'Phone Number',
  'ranks_details': 'Cleanness Ranks Based on Streets',
  'location': 'Select a location',
  'has': 'Has',
  'district': 'District',
  'municipal': 'Municipal',
  'region': 'Region',
  'ward':'Ward',
  'street': 'Street',
  'drain_filter':'Filter Drains',
  'choose_address': 'Choose Address',
  'leader': 'Street leaders',
  'ward_leader':'Ward Leaders',
  'citizen_population': 'Citizen population distribution',
  'registered': 'Registered Users',

  //buttons
  'send': 'Generate Report',
  'submit': 'Submit',
  'cancel': 'Cancel',
  'first':'First',
  'previous': 'Previous',
  'next': 'Next',
  'last': 'Last',
  'alert': 'Alert VEO',
  'send_alert': 'Send Alert Messages',
  'send_awareness': 'Send Awareness Messages',
  'veo': 'Send message to VEO',
  'filter': 'Filters',
  'submitted': 'Submitted',
  'progress': 'Processing',
  'done': 'Done',
  'archive': 'Archived',
  'all_button': 'All',


  /*notification*/
  'message':'A message has been sent',
  'admin': 'Admin Dashboard Space',
  'alert_user': 'Alert message',
  'alert_message': 'Notify your citizens that the rain season is coming and they have make sure that their drains are clean.',
  'send_message': 'Choose the kind of messages you want to send ',
  'aware_user': 'Awareness message',
  'awareness_message':'Send awareness messages to your citizens. You can tell them about the importance of cleanness in their environment, or randomly inform them about something concerning cleanness in their areas.',
  'modify': 'Modify',
  'send_msg': 'Send',
  'box-msg': 'the message in the message box ',
  'or': 'Or',
  'no_status': 'No',
  'yes_status': 'Yes',
 /*Street Reports */
 'street-report':'Cleanliness Report in ',
//  footer
  'copyright': 'Copyright',
  'all-right':'All rights reserved.'
};
