export const LANG_SW_NAME ='sw';

export const LANG_SW_TRANS = {
  'login': 'Ingia',
  'signin': 'Ingia',
  'register': 'Sajili',
  'signout': 'Ondoka',
  'username': 'Namba ya simu',
  'password': 'Neno-siri',
  'placeholder_username': 'Ingiza namba ya simu',
  'placeholder_password': 'Ingiza neno-siri',
  'clean':'Misafi',
  'all': 'Mitaro Yote',
  'dirty': 'Michafu',
  'unknown': 'Haijulikana',
  'citizens': 'Wananchi',
  'not_adopted': 'Mitaro isiyo na watu',
  'need_help_report': 'Ripoti ya mitaro inayohitaji msaada',
  'adopted': "Mitaro iliyotwaliwa",
  'need': 'Mitaro inayohitaji msaada',
  'others': 'Mingineyo',

  /* need help translation*/
  'need_help': 'Msaada ',
  'button_pending': 'Thibitisha',
  'button_resolve': 'Tatua',
  'resolved': 'limeshugulikiwa',
  'approved': 'limethibitishwa',
  'submitted': 'limewasilishwa',
  'pending': 'limethibitishwa',
  'need_help_opened': 'Limewasilishwa',
  'need_help_pending': 'Limethibitishwa',
  'need_help_resolved': 'Limetatuliwa',
  'need_help_category': 'Msaada Unaohitajika',
  'change_status_column': 'Badili Hali',
  'need_help_status': 'Hali',
  'not_yet': 'Bado',
  'status_change_description': 'Maelezo kutokana na ubadilishaji wa hali',
  'status_change_placeholder': 'Sio lazima kujaza',
  'need_help_description_submit': 'Sawa',
  'need_help_description_cancel': 'Ghairi',

    /* Need help graph transilation */
    'graph_title': 'Mchakato wa Uhugulikiwaji wa maombi ya misaada katika mitaro',
    'need_help_graph': 'CHATI YA MAOMBI YA MISAADA YA MITARO',

    /* filters translation*/
    'choose_municipal': 'Chagua Manispaa',
    'choose_ward': 'Chagua Kata',
    'choose_street': 'Chagua Mtaa',
    'choose_status': 'Chagua Hali',

    /*side-menu translation*/
  'dashboard': 'Dashibodi',
  'map' : 'Fungua ramani',
  'ranks': 'Uwiano',
  'report': 'Ripoti',
  'view_drain': 'Ona mitaro',
  'notification': 'Tuma Taarifa',
  'welcome': 'Karibu',

  /*content translations*/
  'title_dashboard': 'Ripoti ya usafi wa mitaro ',
  'title_drains': 'Mitaro iliyochukuliwa  Dar es salaam',
  'title' :'Taarifa ya Jumla ya Usafi',
  'results': 'Matokeo',
  'id': 'Namba',
  'address': 'Mtaa/Mahala',
  'name': 'Jina',
  'full_name': 'Jina kamili',
  'report_made': 'Iliripotiwa',
  'claimed': 'Iliyotwaliwa',
  'phone_number':'Namba ya Simu',
  'drain_no': 'Namba ya mtaro',
  'help': 'Maelezo kwaundani',
  'help_category': 'Aina ya msaada',
  'extra': 'Maelezo zaidi',
  'ranks_details': 'Nafasi za usafi kulingana na mitaa',
  'location': 'Chagua Eneo/Hali',
  'has': 'ina',
  'district': 'Wilaya',
  'municipal': 'Manispaa',
  'street': 'Mtaa',
  'region':'Mkoa',
  'ward': 'Kata',
  'drain_filter':'Mgawanyo wa Mitaro',
  'choose_address': 'Chagua Eneo/Mtaa',
  'leader': 'Viongozi wa mtaa',
  'registered': 'Wananchi waliosajiliwa',
  'ward_leader':'Viongozi wa Kata',
  'citizen_population': 'Mgawanyiko wa watu',


  /*button*/
  'send': 'Tuma',
  'submit':'Wasilisha',
  'cancel': 'Ghairi',
  'first':'mwanzo',
  'previous': 'nyuma',
  'next': 'mbele',
  'last': 'mwisho',
  'alert': 'Mtaarifu VEO',
  'send_alert': 'Ujumbe wa tahadhari',
  'send_awareness': 'Tuma taarifa muhimu',
  'veo': 'Tuma ujumbe kwa VEO',
  'message_send': 'Tuma ujumbe',
  'filter': 'Mgawanyiko',
  'progress': 'Muendelezo',
  'done': 'Kufanyika',
  'archive': 'Vimefanikiwa',
  'all_button': 'Yote',


  /*notification*/
  'message':'Ujumbe umetumwa ',
  'admin': 'Sehemu ya admin',
  'alert_user': 'Ujumbe wa tahadhari',
  'alert_message': 'Watarifu wananchi wako kuwa msimu wa mvua umekaribia hivyo wafanye usafi kwenye mitaro yao pamoja na mazingira yako kwa ujumla.',
  'send_message': ' Chagua aina ya ujumbe unaotaka kuutuma ',
  'aware_user': 'Ujumbe wa Taarifa Muhimu',
  'awareness_message':'Wakumbushe wananchi wako juu ya umuhimu wa kufanya usafi katika mazingira yao au taarifa yoyote inayohusu usafi katika makazi yao.',
  'modify': 'Badilisha',
  'send_msg': 'Tuma',
  'box-msg': 'ujumbe katika sanduku la ujumbe ',
  'verify_title': 'Maombi ya Uongozi',
  'no_verify': 'Hakuna maombi yoyote ya uongozi',
  'action': 'Hatua',
  'or': 'Au',
  'no_status': 'Hapana',
  'yes_status': 'Ndio',


//  footer
  'copyright': 'Hatimiliki',
  'all-right':'Haki zote zimehifadhiwa.'
};
