export const LANG_SW_NAME ='sw';

export const LANG_SW_TRANS = {
  'login': 'Ingia',
  'signin': 'Ingia',
  'register': 'Sajili',
  'signout': 'Ondoka',
  'username': 'Jina la mtumiaji',
  'password': 'Neno-siri',
  'clean':'Misafi',
  'all': 'Mitaro Yote',
  'dirty': 'Michafu',
  'unknown': 'Haijulikani',
  'citizens': 'Wananchi',
  'not_adopted': 'Mitaro isiyo na watu',
  'need_help_report': 'Ripoti ya mitaro inayohitaji msaada',
  'adopted': "Mitaro iliyotwaliwa",
  'need': 'Mitaro inayohitaji msaada',
  'others': 'Mingineyo',
  'need_help': 'Msaada ',
  'button_pending': 'Thibitisha',
  'button_resolve': 'Tatua',
  'resolved': 'limeshugulikiwa',
  'approved': 'limethibitishwa',
  'pending': 'limethibitishwa',
  'need_help_opened': 'Limewasilishwa',
  'need_help_pending': 'Limethibitishwa',
  'need_help_resolved': 'Limetatuliwa',
  'need_help_category': 'Msaada Unaohitajika',
  'change_status_column': 'Badili Hali',
  'need_help_status': 'Hali',
  'not_yet': 'Bado',
  'status_change_description': 'Maelezo kutokana na ubadilishaji wa hali',
  'status_change_placeholder': 'Sio lazima kujaza',
  'need_help_description_submit': 'Sawa',
  'need_help_description_cancel': 'Ghairi',

    /* Need help graph transilation */
    'graph_title': 'Mchakato wa Uhugulikiwaji wa maombi ya misaada katika mitaro',
    'need_help_graph': 'CHATI YA MAOMBI YA MISAADA YA MITARO',
    'select-time': 'Tumia menyu kubadili muda',

    /* filters translation*/
    'choose_municipal': 'Chagua Manispaa',
    'choose_ward': 'Chagua Kata',
    'choose_street': 'Chagua Mtaa',
    'choose_status': 'Chagua Hali',

    /*side-menu translation*/
  'dashboard': 'Dashibodi',
  'map' : 'Fungua ramani',
  'ranks': 'Uwiano',
  'report': 'Ripoti',
  'view_drain': 'Ona mitaro',
  'notification': 'Tuma Taarifa',

  /*content translations*/
  'title_dashboard': 'Ripoti ya usafi wa mitaro ',
  'title_drains': 'Mitaro iliyochukuliwa  Dar es salaam',
  'title' :'Taarifa ya Jumla ya Usafi',
  'results': 'Matokeo',
  'id': 'Namba',
  'address': 'Mtaa/Mahala',
  'name': 'Jina',
  'report_made': 'Iliripotiwa',
  'claimed': 'Iliyotwaliwa',
  'phone_number':'Namba ya Simu',
  'ranks_details': 'Nafasi za usafi kulingana na mitaa',
  'location': 'Chagua Eneo/Sehemu',
  'has': 'ina',
  'district': 'Wilaya',
  'municipal': 'Manispaa',
  'street': 'Mtaa',
  'region':'Mkoa',
  'ward': 'Kata',
  'drain_filter':'Mgawanyo wa Mitaro',
  'choose_address': 'Chagua Eneo/Mtaa',
  'leader': 'Viongozi wa mtaa',
  'registered': 'Wananchi waliosajiliwa',
  'ward_leader':'Viongozi wa Kata',
  'citizen_population': 'Mgawanyiko wa watu',


  /*button*/
  'send': 'Tuma',
  'submit':'Wasilisha',
  'cancel': 'Ghairi',
  'first':'mwanzo',
  'previous': 'nyuma',
  'next': 'mbele',
  'last': 'mwisho',
  'alert': 'Mtaarifu VEO',
  'send_alert': 'Ujumbe wa taahadhari',
  'send_awareness': 'Ujumbe wakuwa makini',
  'veo': 'Tuma ujumbe kwa VEO',
  'message_send': 'Tuma ujumbe',
  'filter': 'Mgawanyiko',
  'submitted': 'Iliyokusanywa',
  'progress': 'Muendelezo',
  'done': 'Kufanyika',
  'archive': 'Vimefanikiwa',
  'all_button': 'Yote',
  'print': 'Chapisha',
  'thetable':'Jedwali',


  /*notification*/
  'message':'Ujumbe umetumwa ',
  'admin': 'Sehemu ya admin',
  'alert_user': 'Ujumbe wa tahadhari',
  'alert_message': ' Msimu wa mvua umekaribia, wataarifu wananchi wako na pia wahakikishe mitaro yao ni misafi.',
  'send_message': ' chagua aina ya ujumbe unaotaka kuutuma ',
  'aware_user': 'UJumbe wa kuwa makini',
  'awareness_message':'Tuma ujumbe kuwa harifu wananchi wako nini umuhimu wa usafi katika mazingira na pia kuwa makini kwenye swala zima la usafi.',
  'modify': 'Badilisha',
  'send_msg': 'Tuma',
  'box-msg': 'ujumbe katika sanduku la ujumbe ',
  'or': 'Au',
  'no_status': 'hapana',
  'yes_status': 'Ndio',

  //Reports
  'report-printing-title': 'Usafi wa Mitaro',
  'general-report-all':'Ripoti ya usafi wa mitaro katika mitaa yote katika kata ya ',
  'general-report-street': 'Ripoti ya Usafi wa mitaro mtaa wa',
  'street-report': 'Ripoti ya Usafi Mtaa wa',

  //  footer
  'copyright': 'Hatimiliki',
  'all-right':'Haki zote zimehifadhiwa.'
};
